# fly.toml app configuration file generated for my-part3-phonebook-backend on 2025-09-11T11:00:36-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-part3-phonebook-backend'
primary_region = 'yyz'

[build]

[env]
  PORT = "3001" # add this

[http_service]
  internal_port = 3001 #updated
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
